<#
  download-ocr.ps1 — Fetch the OPTIONAL OCR / video (heavy) dependencies for OFFLINE install.

  WHY THIS IS A SCRIPT (not pre-vendored): PaddleOCR pulls PaddlePaddle (~100+ MB) and a large
  native dependency tree. Those wheels exceed GitHub's 100 MB/file limit and bloat the repo, and
  cross-building them from Linux is unreliable. So you generate them yourself, natively, here.

  RUN THIS ON A WINDOWS MACHINE THAT HAS INTERNET, with CPython 3.9 (64-bit) installed.
  It downloads win_amd64 / cp39 wheels into .\wheelhouse and writes a pinned requirements-heavy.txt.
  Then copy the whole  offline-bundle\heavy  folder to the offline machine and install (the main
  install-offline.ps1 auto-detects and installs it; or install manually — see this folder's README).

  Usage:
    powershell -ExecutionPolicy Bypass -File download-ocr.ps1                 # OCR only (paddleocr+paddlepaddle)
    powershell -ExecutionPolicy Bypass -File download-ocr.ps1 -IncludeOpenCV  # also video (opencv-python)
    powershell -ExecutionPolicy Bypass -File download-ocr.ps1 -PaddleVersion 2.6.1   # pin paddlepaddle if the latest lacks a 3.9 wheel
#>
param(
  [switch]$IncludeOpenCV,
  [string]$PaddleVersion = ""
)
$ErrorActionPreference = "Stop"

$Here       = $PSScriptRoot
$Wheelhouse = Join-Path $Here "wheelhouse"
New-Item -ItemType Directory -Force -Path $Wheelhouse | Out-Null

# 1. Resolve Python 3.9 (prefer the py launcher so the cp39 wheels match)
$PyExe = $null; $PyArgs = @()
if (Get-Command py -ErrorAction SilentlyContinue) {
    try { & py -3.9 -c "import sys" 2>$null; if ($LASTEXITCODE -eq 0) { $PyExe = "py"; $PyArgs = @("-3.9") } } catch {}
}
if (-not $PyExe -and (Get-Command python -ErrorAction SilentlyContinue)) { $PyExe = "python" }
if (-not $PyExe) { throw "Python not found. Install CPython 3.9.x (64-bit) from python.org and re-run." }

$ver = & $PyExe @PyArgs -c "import sys;print('%d.%d'%sys.version_info[:2])"
if ($ver -ne "3.9") {
    Write-Warning "Selected Python is $ver. For the offline cp39 target, install Python 3.9.x (64-bit)."
}

# 2. Build the package list
$pkgs = @()
if ($PaddleVersion) { $pkgs += "paddlepaddle==$PaddleVersion" } else { $pkgs += "paddlepaddle" }
$pkgs += "paddleocr"
if ($IncludeOpenCV) { $pkgs += "opencv-python" }

Write-Host "Downloading heavy wheels: $($pkgs -join ', ')" -ForegroundColor Cyan
Write-Host "This is large (PaddlePaddle alone is ~100+ MB) and needs internet..." -ForegroundColor DarkGray

# 3. Native pip download (wheels only — required for offline install)
& $PyExe @PyArgs -m pip download --only-binary=:all: --dest $Wheelhouse @pkgs
if ($LASTEXITCODE -ne 0) {
    Write-Warning "A package had no win_amd64 wheel at the resolved version."
    Write-Warning "Common fix: pin PaddlePaddle, e.g.  -PaddleVersion 2.6.1  (try 2.6.x / 2.5.x for Python 3.9)."
    throw "Heavy download incomplete — see messages above."
}

# 4. Write a pinned requirements-heavy.txt from whatever landed (deterministic offline install)
$pins = Get-ChildItem $Wheelhouse -Filter *.whl | ForEach-Object {
    $parts = $_.Name -split '-'; "{0}=={1}" -f $parts[0], $parts[1]
} | Sort-Object -Unique
$header = @"
# requirements-heavy.txt — OPTIONAL OCR/video wheels for CPython 3.9 / win_amd64.
# Auto-generated by download-ocr.ps1. Install offline into the project venv:
#   <repo>\.venv\Scripts\python -m pip install --no-index --find-links wheelhouse -r requirements-heavy.txt
"@
Set-Content -Path (Join-Path $Here "requirements-heavy.txt") -Value ($header + "`r`n" + ($pins -join "`r`n")) -Encoding ascii

$mb = "{0:N0}" -f ((Get-ChildItem $Wheelhouse -Filter *.whl | Measure-Object Length -Sum).Sum / 1MB)
Write-Host ""
Write-Host "Done. $($pins.Count) wheels in $Wheelhouse  (~$mb MB)" -ForegroundColor Green
Write-Host "Next on the OFFLINE machine:"
Write-Host "  - re-run  offline-bundle\install-offline.ps1   (auto-installs heavy if this folder is present)"
Write-Host "  - or:     <repo>\.venv\Scripts\python -m pip install --no-index --find-links `"$Wheelhouse`" -r `"$(Join-Path $Here 'requirements-heavy.txt')`""
