#!/usr/bin/env bash
#
# download-ocr.sh — Fetch the OPTIONAL OCR / video (heavy) dependencies for OFFLINE Linux install.
#
# WHY A SCRIPT (not pre-vendored): PaddleOCR pulls PaddlePaddle (~100+ MB) and a large native tree.
# Those wheels exceed GitHub's 100 MB/file limit and bloat the repo, and PaddlePaddle's Linux wheel
# tags are finicky to cross-build. So you generate them yourself, NATIVELY.
#
# RUN THIS ON A LINUX BOX MATCHING THE TARGET: CPython 3.9, x86_64, glibc — WITH internet.
# It downloads wheels into ./wheelhouse and writes a pinned requirements-heavy.txt. Then copy the
# whole  offline-bundle/linux/heavy  folder to the offline machine; the main install-offline.sh
# auto-detects and installs it (or install manually — see this folder's README).
#
# Usage:
#   bash download-ocr.sh                 # OCR (paddleocr + paddlepaddle)
#   bash download-ocr.sh --opencv        # also video (opencv-python)
#   bash download-ocr.sh --paddle 2.6.1  # pin paddlepaddle if the latest lacks a 3.9 wheel
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WH="$HERE/wheelhouse"; mkdir -p "$WH"

PADDLE="paddlepaddle"; WANT_OPENCV=0
while [ $# -gt 0 ]; do
  case "$1" in
    --opencv) WANT_OPENCV=1 ;;
    --paddle) shift; PADDLE="paddlepaddle==${1:?--paddle needs a version}" ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac; shift
done
PKGS=("$PADDLE" paddleocr)
[ "$WANT_OPENCV" = "1" ] && PKGS+=(opencv-python)

# Resolve Python 3.9 (run natively on a matching box so paddle's real tags resolve)
if command -v python3.9 >/dev/null 2>&1; then PY="python3.9"; else PY="python3"; fi
ver="$("$PY" -c 'import sys;print("%d.%d"%sys.version_info[:2])')"
[ "$ver" = "3.9" ] || echo "WARNING: Python is $ver; for the cp39 offline target run this on a 3.9 box." >&2

echo "Downloading heavy wheels: ${PKGS[*]}"
echo "(large — PaddlePaddle alone is ~100+ MB; needs internet)"

# Native download (no cross flags): on a matching 3.9/x86_64/glibc box this captures whatever
# tag paddle actually publishes (manylinux OR bare linux_x86_64), which cross-flags often miss.
if ! "$PY" -m pip download --only-binary=:all: --dest "$WH" "${PKGS[@]}"; then
  echo "WARNING: a package had no compatible wheel at the resolved version." >&2
  echo "         Common fix: pin PaddlePaddle, e.g.  bash download-ocr.sh --paddle 2.6.1  (try 2.6.x / 2.5.x for 3.9)." >&2
  exit 1
fi

# Write a pinned requirements-heavy.txt from whatever landed (deterministic offline install)
{
  echo "# requirements-heavy.txt — OPTIONAL OCR/video wheels for CPython 3.9 / x86_64 / manylinux."
  echo "# Auto-generated by download-ocr.sh. Install offline into the project venv:"
  echo "#   <repo>/.venv/bin/python -m pip install --no-index --find-links wheelhouse -r requirements-heavy.txt"
  for f in "$WH"/*.whl; do b="$(basename "$f")"; echo "${b%%-*}==$(echo "$b" | cut -d- -f2)"; done | sort -u
} > "$HERE/requirements-heavy.txt"

mb="$(du -sm "$WH" | cut -f1)"
echo
echo "Done. Wheels in $WH (~${mb} MB)."
echo "Next on the OFFLINE machine:"
echo "  - re-run  offline-bundle/linux/install-offline.sh   (auto-installs heavy if this folder is present)"
echo "  - or:     <repo>/.venv/bin/python -m pip install --no-index --find-links \"$WH\" -r \"$HERE/requirements-heavy.txt\""
